version: '3.8'

services:
  ita3d-website:
    build: .
    container_name: ita3d-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Required environment variables for the application
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_TO_ADDRESS=${EMAIL_TO_ADDRESS}
    volumes:
      # Optional: Mount for persistent logs (uncomment if needed)
      # - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Labels for TrueNAS Scale UI
      - "traefik.enable=true"
      - "traefik.http.routers.ita3d.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.ita3d.tls=true"
      - "traefik.http.routers.ita3d.tls.certresolver=letsencrypt"
      - "traefik.http.services.ita3d.loadbalancer.server.port=3000"

networks:
  default:
    name: ita3d-network 